### ISSUE TITLE
Add non-JS API documentation

### ISSUE THREAD

**Issue by Arsen6331** [LemmyNet/lemmy-docs#151]
Currently, Lemmy's documentation links to `lemmy-js-client`. This makes it very difficult to make a client in any language other than JS. I would specifically like to create a Go client.

I think it would be better to have language-agnostic documentation explaining what to send and what the responses will look like. Maybe this documentation can be automatically generated?

**Comment by Nutomic** [comment]
Unfortunately there is a lack of tooling to generate API docs from Rust code, so it doesnt seem easy. What you can do for now is look at the structs which define API requests and responses, you can find them [here](https://github.com/LemmyNet/lemmy/blob/main/crates/api_common/src/post.rs) and in other files in that directory.

**Comment by dessalines** [comment]
> I think it would be better to have language-agnostic documentation explaining what to send and what the responses will look like. Maybe this documentation can be automatically generated?

All of the exact types and actions are listed in those lemmy-js-client docs, and they are auto-generated. You could probably almost copy-paste the lemmy-js-client codebase and convert it to go fairly easily. 

https://join-lemmy.org/api/classes/LemmyHttp.html

We used to maintain agnostic docs, but it was too difficult to keep up with changes. So lemmy-js-client is the reference.

**Comment by Arsen6331** [comment]
Thanks, that should be enough for me

**Comment by Nutomic** [comment]
Btw you can also join our [Matrix chat](https://matrix.to/#/#lemmydev:matrix.org) if you have any questions.

**Comment by Arsen6331** [comment]
Thanks, I already have it successfully logging in, and I'm just converting the structs from Rust to Go so I can implement the other endpoints. If I have any questions, I'll join.
