### ISSUE TITLE
Administration - Backup and Restore Update

### ISSUE THREAD

**Issue by tracyspcy** [LemmyNet/lemmy-docs#16]
1. To get psql for my docker instead of `docker-compose exec postgres psql -U lemmy` as is stated in guide, at least in my case I had to use `docker-compose exec postgres psql -U username db_name`. Otherwise I got errors:
`sudo docker-compose exec postgres psql -U lemmy` returns `psql: error: FATAL: role "lemmy" does not exist  `
`sudo docker-compose exec postgres psql -U user ` returns `psql: error: FATAL: database "user" does not exist`
So in my case, lemmy is a db name and user - user.

2. When I follow a guide in order to change a domain name and use commands from the guide such as `delete from post_aggregates_fast;` or `insert into post_aggregates_fast select * from post_aggregates_view;` I constantly got errors: `ERROR: relation "post_aggregates_fast" does not exist` . 
Is it outdated info in your guide or there is a problem I should fix? (In my case I have just ignored these errors and domain name was successfully changed).

https://lemmy.ml/docs/en/administration/backup_and_restore.html?highlight=postgres#changing-your-domain-name

**Comment by dessalines** [comment]
I can't really do anything about the first one because if someone's going to customize their DB username, they won't be able to run that command.

The second one just needs some things removed, as we've removed those views. I'll do that now.
