### ISSUE TITLE
Code of conduct not showing up?

### ISSUE THREAD

**Issue by artiblaster** [LemmyNet/lemmy-docs#20]
This link works, https://join.lemmy.ml/docs/en/code_of_conduct.html, but it doesn't have the "Where can i find the "Citizen Code of Conduct"? #17" fix. AFAIK, #17 has been fixed, though i know nothing about github.

 Nutomic link doesn't work in multiple browsers.
" Nutomic commented 4 days ago

Our code of conduct is here: https://lemmy.ml/docs/en/code_of_conduct.html"

**Comment by dessalines** [comment]
This needed to wait for me to deploy it, thx for reminding.
