### ISSUE TITLE
"Peer authentication failed for user lemmy"

### ISSUE THREAD

**Issue by mtekman** [LemmyNet/lemmy-docs#220]
This is an issue to do with the postgresql using peer authentication and not password ("md5") authentication.

## Solution

The solution is to create a relevant line in your `pg_hba.conf` file (usually found in `/etc/postgresql/`).

Change:
```
# "local" is for Unix domain socket connections only
local   all             all                                     peer
```

to:

```
# "local" is for Unix domain socket connections only
local   lemmy           lemmy                                   md5
local   all             all                                     peer
```

Or, one liner:

`sed -i -r '/^local\s+all\s+all\s+peer/i local   lemmy           lemmy                                   md5' /etc/postgresql/15/main/pg_hba.conf`

## Commentary

This ensures that only the "lemmy" database under user "lemmy" accepts passwords. 
Note that this new line must be added **above** the unedited line, in order for it to work.

After this, restart your postgres (`sudo systemctl restart postgresql`), and things should work

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy-docs/pull/221
