### ISSUE TITLE
Suggested backup script is somewhat dangerous

### ISSUE THREAD

**Issue by SorteKanin** [LemmyNet/lemmy-docs#262]
The suggested script pipes into gzip, potentially ignoring any errors. If the docker exec fails for whatever reason, gzip just ignores the error and returns 0.

Perhaps something like this should be used instead:
```
set -euo pipefail
file_name=lemmy_dump_$(date +%Y-%m-%d"T"%H_%M_%S).sql
docker-compose exec postgres pg_dumpall --clean -U lemmy > ${file_name}
gzip ${file_name}
```

**Comment by dessalines** [comment]
You mean if pg_dumpall had errors? I can't see why that would occur, or if someone wouldn't notice that their output takes up only a few kb.

**Comment by SorteKanin** [comment]
Well it could happen for instance if you run out of disk space. It happened in my case as well when my docker container's name changed. In any case, it can fail.

>someone wouldn't notice that their output takes up only a few kb.

You're unlikely to check this manually if you've set up automatic backups.

**Comment by dessalines** [comment]
I'm open to PRs to change it, but the script does currently work as-is.
