### ISSUE TITLE
Json Objects in the doc are not loaded in correctly

### ISSUE THREAD

**Issue by BentiGorlich** [LemmyNet/lemmy-docs#283]
For example: https://join-lemmy.org/docs/contributors/05-federation.html#report-post-comment-or-private-message
To see the json object I have to go to the lemmy repo and navigate to the path that is shown in the doc.
It would be nice if it was loaded in correctly. I suspect there to be just a syntax error with it right?

**Comment by dessalines** [comment]
@Nutomic I'm not sure how the `update-includes.sh` works.

**Comment by Nutomic** [comment]
Ah the server wasnt running update-includes script when building the site. Fixed now, thanks for pointing it out.

**Comment by BentiGorlich** [comment]
nice, thanks for fixing it so fast :)
