### ISSUE TITLE
[Bug]: Incorrect pathing in copy binary command in "from scratch" doc

### ISSUE THREAD

**Issue by Spl0itable** [LemmyNet/lemmy-docs#285]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Hello, the from scratch doc: https://join-lemmy.org/docs/administration/from_scratch.html

Has the following instruction:

```
Then copy the binary.

sudo cp target/release/lemmy_server /opt/lemmy-server/lemmy_server
```

However, the path `/opt/lemmy-server/lemmy_server` is not correct and should be `/opt/lemmy/lemmy-server/lemmy_server`

### Steps to Reproduce

See summary

### Technical Details

See summary

### Version

0.18.5

**Comment by Nutomic** [comment]
The file is [here](https://github.com/LemmyNet/lemmy-docs/blob/main/src/administration/from_scratch.md), you can make a pull request to fix those things.
