### ISSUE TITLE
Object Storage for embedded pict-rs on from scratch install?

### ISSUE THREAD

**Issue by Spl0itable** [LemmyNet/lemmy-docs#287]
I saw this post about switching lemmy to using object storage: https://lemmy.studio/post/93370

I also want to do the same. However, I set up a new lemmy server using source that has an embedded pict-rs https://join-lemmy.org/docs/administration/from_scratch.html

For some reason I cannot override the local upload.

I’ve tried editing the lemmy config .hjson file like this: https://pastebin.com/pDE0wiJ4

I also tried editing the systemd unit file like this: https://pastebin.com/rXb5YE95

But if I deviate from localhost upload, it breaks. Also, when I edit the hjson file with the env vars it causes lemmy service to fail.

Any suggestions? Thanks!

**Comment by dessalines** [comment]
The pictrs configuration must be in the docker-compose.yml , not the lemmy.hjson

**Comment by Spl0itable** [comment]
> The pictrs configuration must be in the docker-compose.yml , not the lemmy.hjson

Ah yes this was it, thank you! Now, where am I able to add my custom hostname (files.example.com) for the bucket so the uploaded files aren't using localhost address? 

I tried changing the `http://localhost:8080/` in the hjson file and the `127.0.0.1:8080` in the systemd unit file, but those don't seem to be it.

**Comment by dessalines** [comment]
Here's some of our vars in the pictrs docker-compose environment block. Outside of that I don't know your question, you'll have to ask in a pictrs chat.

lemmy.hjson : 
```
pictrs: {
  url: "http://pictrs:8080/" # This will be different if you're not using docker.
  ...
```

docker-compose.yml :

```
# Object storage config
- PICTRS__STORE__TYPE=object_storage
- PICTRS__STORE__ENDPOINT=https://s3....
- PICTRS__STORE__BUCKET_NAME=...
- PICTRS__STORE__REGION=...
- PICTRS__STORE__ACCESS_KEY=...
- PICTRS__STORE__SECRET_KEY=...
- PICTRS__STORE__USE_PATH_STYLE=false
```

**Comment by Spl0itable** [comment]
@dessalines No worries, I've got the object storage working. I have my s3 compliant bucket using `files.example.com` subdomain. Would the `url` param in the lemmy config need to change?

Is there some special config setting that will allow fetching the file hash over this subdomain rather than the localhost and/or apex domain? Thanks!

**Comment by Spl0itable** [comment]
Actually, @dessalines you can disregard my last request I'll be ok with it not using a custom subdomain to deliver the uploads. It's working correctly. Very much appreciate the help and confirming I did in fact need to edit the docker-compose.yml file despite building from source. Thanks!

**Comment by Spl0itable** [comment]
@dessalines Sorry to re-open this, but have had a significant update on this.

It appears my initial thought that adding the env vars to the docker-compose.yml file made the object storage work with my Lemmy instance and using Cloudflare R2 bucket (s3 compliant storage).

However, it became apparent that simply adding those to the config file did not allow objects to be uploaded. Instead, with the "from scratch" install and with the embedded pict-rs, I need to add the object storage deets to the the `/etc/systemd/system/lemmy.service` systemd file.

Only when those env vars were added to the systemd file did the media get uploaded to the object storage bucket. However, when the media is fetched, it presents an error.

Uploaded media shows a `{"msg":"Error in store"}` response, ex: https://h4x0r.host/pictrs/image/92426ee1-8b2e-4edd-bbd5-b4a31455f78b.jpeg

I suspect that pict-rs is unable to use the sled repo db file to correctly match the hash for the image to the object storage. Any idea how I might be able to resolve this? Thanks!

**Comment by dessalines** [comment]
Its possible you're using the wrong env vars for that version of pictrs, they've changed recently. I'd suggest asking these in the pictrs chat #pictrs:matrix.asonix.dog
