### ISSUE TITLE
docker compose nginx conf error 

### ISSUE THREAD

**Issue by AXCWG** [LemmyNet/lemmy-docs#317]
Inside nginx conf provided by the docker compose installation method tutorial there is a variable which was from vars.yml which is from ansible, nowhere mentioned inside the document about that variable and I spend a whole night on debugging nginx because of the var and every time I started the nginx container it just said something like "need a ";"". I'm not very familiar with nginx so I thought that'd be something included by nginx or something, but no. 

please edit the doc and mention the need of substitude the variable.

**Comment by dessalines** [comment]
No idea what this means, but please use the support channels recommended and be more specific.
