### ISSUE TITLE
Broken link in left-hand navigation menu

### ISSUE THREAD

**Issue by DeathByDenim** [LemmyNet/lemmy-docs#84]
When viewing the documentation on https://join-lemmy.org/docs/en/, the entry "4.2. API reference" points to https://join-lemmy.org/docs/en/https://join.lemmy.ml/api/index.html.

This seems to be because the link in src/en/SUMMARY.md for `[WebSocket API](https://join.lemmy.ml/api/index.html)` is interpreted as a local file instead of an actual link when compiling the book. This may be an issue with mdbook though.

**Comment by dessalines** [comment]
I'm not too sure abt this one, @Nutomic

**Comment by Nutomic** [comment]
Found two mdbook issues about this: https://github.com/rust-lang/mdBook/issues/919 https://github.com/rust-lang/mdBook/issues/1354. tl;dr its not supported, I guess the workaround is to make a markdown page with nothing but that link. Will make a PR for that.
