### ISSUE TITLE
Documentation unclear on About/Goals document

### ISSUE THREAD

**Issue by mugcake** [LemmyNet/lemmy-docs#88]
The document `goals.md` is somewhat unclear. It seems like a TODO list instead of project's goals. The **"Resources / Potential Libraries"** part would be better in some document in the `Contribution` section or as a separate document in the same section, e.g. `resources.md`

**Comment by Nutomic** [comment]
True, it sounds like @dessalines wrote that before starting to develop the project. I think we should either remove it, or rewrite it completely.
