### ISSUE TITLE
Install and run without docker

### ISSUE THREAD

**Issue by Rundik** [LemmyNet/lemmy-docs#9]
It would be great to have instructions to install lemmy without docker-like environments

**Comment by Nutomic** [comment]
Actually I think this would be fine to include in the Lemmy docs, given that there is a big disclaimer saying that its not a recommended installation method, and not to ask the Lemmy developers for help if there are problems.

**Comment by dessalines** [comment]
Ya, as long as there's a big disclaimer at the top I'm fine with including it.
