### ISSUE TITLE
Rewrite instructions for manual installation

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-docs#95]
Its written for a rather obscure distro (Gentoo), and is overly long. I think it would be best to rewrite it from scratch, and for Ubuntu, because everyone can understand that. Besides, iframely should be removed (#92), and Lemmy installed from crates.io (https://github.com/LemmyNet/lemmy/pull/1674).

**Comment by ncorder** [comment]
It would be a good idea to add documentation for a Debian based distro alongside for FreeBSD/OpenBSD as is currently setup for Peertube ( although they have steps for many OSes ).

**Comment by Nutomic** [comment]
This is already fixed, the instructions are now for Ubuntu.
